### ISSUE TITLE
vim-themisと組み合わせてテスト実行すると「E475: 無効な引数です」が出ます

### ISSUE THREAD

**Issue by tyru** [kannokanno/vmock#1]
https://gist.github.com/tyru/02fe73df6d316fa28c09/893fa4080778598766103bd7ea399e41d629bfdd

使い方等間違っているでしょうか？
再現手順は以下の通りです。
1. open-browser.vimのリポジトリにて `test/01-basic.vim` に上記Gistのファイルを置く
2. コマンドラインで `themis --runtimepath ~/.vim/bundle/vmock` を実行

**Comment by kannokanno** [comment]
ご報告ありがとうございます！
都合により後日になってしまいますが確認致します。

**Comment by tyru** [comment]
全然構わないです！
ありがとうございます。

**Comment by kannokanno** [comment]
## 原因

原因としては`g:Process.system`の実体がスクリプトローカルな関数のためでした。

``` vim
let g:Process = vital#of('openbrowser').import('Process') | function g:Process.system
" E123: 未定義の関数です: <SNR>370_system
```

vmockではスクリプトローカルな関数はモックに出来ないためエラーとなっていました。

## 対応

綺麗ではないですが、グローバルな関数でラップすると動かせます。
- 実装コード
  
  ``` vim
  function! openbrowser#system(...)
      " g:Process.systemの処理を呼ぶ
  endfunction
  ```
  - `g:Process.system`を読んでいた部分を`openbrowser#system`に変更する
- テストコード
  
  ``` vim
  scriptencoding utf-8
  
  let s:suite = themis#suite('basic')
  
  function! s:suite.before()
      let g:Process = vital#of('openbrowser').import('Process')
      call openbrowser#__inject__('Process', g:Process)
  endfunction
  
  function! s:suite.open()
      try
          call vmock#mock('openbrowser#system')
          call openbrowser#open('http://example.com/')
          call vmock#verify()
      catch
          echoerr v:exception
      finally
          call vmock#clear()
      endtry
  endfunction
  ```
- 実行結果
  
  ```
  (tmp)/Users/kanno/.vim/bundle/open-browser.vim% themis --runtimepath ~/.vim/bundle/vmock
  1..1
  ok 1 - basic open
  
  # tests 1
  # passes 1
  ```
  - `call vmock#mock('openbrowser#system')`の行を外すとexample.comが開くので、正常にモック化されていることを確認できます

**Comment by tyru** [comment]
迅速な調査大変ありがとうございます！
試してみた所、関数にabortが付いているとエラーになるようでした。
`openbrowser#__system__()`のabortを消してみた所、テストは正常に動作しました。
（別issueで挙げた方が良いでしょうか？）

```
$ themis --runtimepath ~/.vim/bundle/vmock
1..1
not ok 1 - basic open
# function 85() dict  Line:9  (~/.vim/bundle/open-browser.vim/test/01-basic.vim)
# Vim(echoerr):Vim(function):E475: 無効な引数です: openbrowser#__system__(... abort)
# call vmock#mock#called('openbrowser#__system__', [a:... abort])
# return vmock#mock#return('openbrowser#__system__')
# endfunction

# tests 1
# passes 0
# fails 1
```

**Comment by kannokanno** [comment]
ありがとうございます！

> 試してみた所、関数にabortが付いているとエラーになるようでした。

おお、そうなんですね。。。
こちらで起票しておきます！

**Comment by tyru** [comment]
それ以外は以下でテストコード追加して確認したので、クローズします。ありがとうございました！
https://github.com/tyru/open-browser.vim/issues/16

**Comment by kannokanno** [comment]
ありがとうございます！
