### ISSUE TITLE
vmock can't work on Vim 8

### ISSUE THREAD

**Issue by tyru** [kannokanno/vmock#5]
AppVeyor 上で Vim 8 だとテストが fail するようです。
https://github.com/tyru/caw.vim/pull/75
https://ci.appveyor.com/project/tyru/caw-vim/build/151/job/ee3l3wdruwy8hl19
https://ci.appveyor.com/project/tyru/caw-vim/build/151/job/fjic60c06ivp9wdj

**Comment by tyru** [comment]
`autoload/vmock/function_define.vim` で `:function! %s(%s) ...` といった文字列が組み立てられ [`:execute` で実行されている](https://github.com/kannokanno/vmock/blob/18b04902fb81e295c6f74369503cb28ae549907c/autoload/vmock/function_define.vim#L132)ようですが、ファイル名が違うのでエラーになります。

PR を送ろうかと思いましたが、どのような対処をしていいか分からなかったため (本来この処理に来てしまうのがおかしい？) 、issue を立てました。

**Comment by tyru** [comment]
一応、themis のスタックトレースも貼っておきます。
`vmock#function_define#override()` で `caw#getline` の function を作ろうとしてエラーになっています。

```
C:\config\dotfiles\dotfiles\.vim\bundle\caw.vim>themis test\actions\box.vim
1..3
not ok 1 - actions.box comment
# function themis/Runner.emit(name, ...) abort dict  Line:3  ()
# function <SNR>7_call(obj, key, args) abort  Line:4  ()
# function 32(event, args) abort dict  Line:4  ()
# function <SNR>7_call(obj, key, args) abort  Line:2  ()
# function themis/style['basic'].event.after_test(bundle, name) abort dict  Line:2  ()
# function 92() abort dict  Line:2  ()
# function vmock#clear()  Line:1  ()
# function vmock#container#clear()  Line:3  ()
# function 108() dict  Line:2  ()
# function <SNR>26_remembar_define(original_define)  Line:2  ()
# function vmock#function_define#override(funcname, arg_names, body)  Line:8  ()
# Vim(function):E746: 関数名がスクリプトのファイル名と一致しません: caw#getline
not ok 2 - actions.box comment_indent_noexpandtab
# function 94() abort dict  Line:2  ()
# Vim(call):E488: 余分な文字が後ろにあります
not ok 3 - actions.box comment_indent_expandtab
# function 95() abort dict  Line:8  ()
# Vim(call):E488: 余分な文字が後ろにあります

# tests 3
# passes 0
# fails 3
```

**Comment by kannokanno** [comment]
ご報告ありがとうございます。

エラー自体は「モックにした関数を元に戻すために再定義する」ところで落ちていますね...。
この関数(`vmock#function_define#override()`)が呼ばれることは期待通りのはずです。
(`vmock#clear()`を呼ぶと、定義を元に戻すためにここに到達します)
なんで落ちるようになったんだろう...。

ちょっと調べます 🙇

**Comment by kannokanno** [comment]
ちゃんとした原因は分かっていないのですが、現象としては次のような感じでした。

- 元の定義 -> mockに再定義は成功
- mock -> 元の定義に再定義が失敗
- mockにした後で実際に`caw#getline`を呼び出すと再定義できなくなる
- verifyのためにmock呼び出し時の引数を内部で持っているが、どうやらその参照が残っていると再定義できないのかも


ということで以下のように修正すると、ローカルでは`caw.vim/test`がpassすることを確認しました。

```diff
diff --git a/autoload/vmock/matcher/with_group.vim b/autoload/vmock/matcher/with_group.vim
index c955691..bbf30b7 100644
--- a/autoload/vmock/matcher/with_group.vim
+++ b/autoload/vmock/matcher/with_group.vim
@@ -78,7 +78,7 @@ function! s:make_prototype(matchers)
   endfunction

   function! obj.recording(args)
-    let self.__actual_args = a:args
+    let self.__actual_args = deepcopy(a:args)
   endfunction

   function! obj.validate()
```

vmock自体のテストをthemisで書き換えてからpushするので、少々お待ちください。

**Comment by kannokanno** [comment]
> vmock自体のテストをthemisで書き換えてからpushするので、少々お待ちください。

現在のテスト(vimtest)でもvim8だと、いくつか落ちるようになっていて修正が面倒そうだったので後回しに...。

@tyru 
passするように修正したものをmasterにpushしたので、再度お試し頂けますでしょうか。

**Comment by tyru** [comment]
ありがとうございます。試してみます。

**Comment by kannokanno** [comment]
補足メモ。

> 現在のテスト(vimtest)でもvim8だと、いくつか落ちるようになっていて修正が面倒そうだったので後回しに...。

判明しているのはテスト用のコードで問題があっただけで、ロジックのエラーではない(全部は確認していない)

- vimtest自体のエラーっぽい内容
- テスト用に設定しているグローバル関数が`g:`となっている

**Comment by tyru** [comment]
ありがとうございます！
無事テストが全て pass しました！
https://github.com/tyru/caw.vim/pull/75
