### ISSUE TITLE
可変長引数を持つ関数をモックにするとエラーになる

### ISSUE THREAD

**Issue by zeero** [kannokanno/vmock#6]
こんにちは。

タイトルの通りですが、以下のslack_files#api#helper#post関数をモックにしたところ、テスト実行時に「E116: Invalid arguments for function vmock#mock#called」が発生しました。

[vim-slack_files/helper.vim at master · zeero/vim-slack_files](https://github.com/zeero/vim-slack_files/blob/master/autoload/slack_files/api/helper.vim)

slack_files#api#helper#postの引数から可変長引数を削除すると、テストが正常終了したので可変長引数を持っていることが問題かなと推測しました。
テストコードは以下の通りです。（themisを使っています）

```vim
let s:suite = themis#suite('Test for autoload/slack_files/api/auth.vim -')
let s:assert = themis#helper('assert')

function! s:suite.test_1()
  let token = 'dummy'
  try
    call vmock#mock('slack_files#api#helper#post').with('auth.test', {'token': token}).return('mock value').once()
    call slack_files#api#auth#test(token)
    call s:assert.true(1)

    call vmock#verify()
  catch
    echoerr v:exception
  finally
    call vmock#clear()
  endtry
endfunction
```

**Comment by kannokanno** [comment]
むむ。情報ありがとうございます。
少し後日になりそうですが、確認致します。

**Comment by zeero** [comment]
コメントありがとうございます。
よろしくお願い致します。

**Comment by kannokanno** [comment]
memo: 構造を忘れたりしていてメンテがきついので #7 対応後に着手

**Comment by zeero** [comment]
長くなりそうだったのでコードを追ってみました。

autoload/vmock/function_define.vim の154行目

```vim
function! s:make_called_variable(arg_names)
  if len(a:arg_names) < 1
    return '[]'
  endif
  if a:arg_names[0] ==# '...'
    return 'a:000'
  endif
  return '[' . join(map(deepcopy(a:arg_names), "\"a:\" . v:val"), ',') . ']'
endfunction
```

こちらで可変長引数についての考慮は入っていたようですが、引数が可変長引数のみの場合を想定していて、通常の引数と可変長引数が両方使われているケースを想定していなかったことがエラーの原因のようです。
最後のreturn文を

```
return '[' . join(map(deepcopy(a:arg_names), '"a:" . substitute(v:val, "^\\.\\.\\.$", "000", "")'), ',') . ']'
```

のように変えたところ正常に動作することが確認できました。ご参考まで。

**Comment by kannokanno** [comment]
おお。ありがとうございます！
では後で一旦これを適用したのをmasterに上げるようにします。
(themis移行は別で進めることにする)

**Comment by kannokanno** [comment]
@zeero 
ご提案頂いた内容でmasterを変更しました。

**Comment by zeero** [comment]
早速の対応ありがとうございます！
こちらでも変更内容を取り込んで正常に動作することが確認できました！
イシュークローズさせて頂きます。
